[package]
name = "ast-grep-lsp"
version = "0.1.0"
authors = ["Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>"]
edition = "2021"
description = "Language Server for ast-grep"
keywords = ["ast", "lsp", "codemod", "search", "rewrite"]
license = "MIT"
repository = "https://github.com/HerringtonDarkholme/ast-grep"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast-grep-core = { version="0.1.0", path = "../core" }
