[package]
name = "ast-grep-core"
version = "0.1.0"
authors = ["Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>"]
edition = "2021"
description = "Search and Rewrite code at large scale using precise AST pattern"
keywords = ["ast", "pattern", "codemod", "search", "rewrite"]
license = "MIT"
repository = "https://github.com/HerringtonDarkholme/ast-grep"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.6"
tree-sitter-c = "0.20.1"
tree-sitter-go = "0.19.1"
tree-sitter-html = "0.19.0"
tree-sitter-java = "0.19.0"
tree-sitter-javascript = "0.20.0"
tree-sitter-kotlin = "0.2.11"
tree-sitter-lua = "0.0.11"
tree-sitter-python = "0.20.2"
tree-sitter-rust = "0.20.1"
tree-sitter-swift = "0.3.0"
tree-sitter-typescript="0.20.1"
